### ISSUE TITLE
passing object to _onCheckCallback doesnt work

### ISSUE THREAD

**Issue by yhendry** [mhollweck/react-native-item-checkbox#5]
Hi Maria,
I've been trying to able to get the list of selected checkboxes using this component , however i found that if I try to pass this._onCheckCallback('checkbox1') and try to log or alert it, it always shows undefined. I need to find a way to identify which checkbox being selected, is there any alternative way of doing it?

**Comment by npomfret** [comment]
```
onCheck={() => this.select(someIdentifier)}
onUncheck={() => this.deselect(someIdentifier)}
```

**Comment by mhollweck** [comment]
You could also use a reference to the checkbox (see here https://facebook.github.io/react/docs/more-about-refs.html)

`<ItemCheckbox ref={(c) => this._boxA = c} />`

and then
`this._boxA.state.checked`

But I'm adding a isChecked function to this right now!
