### ISSUE TITLE
Warning: Failed propType: Invalid props.style key `color` supplied to `View`.

### ISSUE THREAD

**Issue by sibelius** [mhollweck/react-native-item-checkbox#7]
Warning: Failed propType: Invalid props.style key `color` supplied to `View`.
Bad object: {
  "borderWidth": 1,
  "borderColor": "red",
  "alignSelf": "flex-start",
  "overflow": "hidden",
  "color": "white",
  "flex": 1,
  "width": 21,
  "height": 21
}

I'm using https://github.com/oblador/react-native-vector-icons and React Native ^0.18.1

**Comment by kobePer** [comment]
Have you had any luck in solving this issue?

**Comment by sibelius** [comment]
@kobePer check it out this: https://github.com/bartonhammond/snowflake/blob/master/src%2Fcomponents%2FItemCheckbox.js
